### ISSUE TITLE
Can't use import in server.js?

### ISSUE THREAD

**Issue by luojinghui** [cereallarceny/cra-ssr#1]
Run your example, error after `yarn serve`
```
yarn run v1.1.0
warning package.json: No license field
$ NODE_ENV=development node server/index.js
/data/build/dev/react/cra-ssr/server/server.js:1
(function (exports, require, module, __filename, __dirname) { import bodyParser from 'body-parser';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Module._extensions..js (module.js:623:10)
    at Object.require.extensions.(anonymous function) [as .js] (/data/build/dev/react/cra-ssr/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

nodejs version: 8.8

Is it because babel-register does not work?

**Comment by cereallarceny** [comment]
I'm relatively certain this is completely unrelated to this repo.  It sounds like your Babel or CRA set up isn't correct.  Do you have Babel set up correctly on your machine?  What version of CRA are you running?

**Comment by luojinghui** [comment]
@cereallarceny My CRA version is: 1.4.3, I have not configured on my machine about babel things, what is the need to configure it?How to config,thanks.

**Comment by cereallarceny** [comment]
@luojinghui I'm closing this issue, it's unrelated to this repo.  Please set up CRA properly and install Babel: http://babeljs.io/
